[project]
name = "tubevit"
version = "0.1.0"
description = 'An unofficial implementation of TubeViT in "Rethinking Video ViTs: Sparse Video Tubes for Joint Image and Video Learning".'
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.2",
    "lightning>=2.6.1",
    "matplotlib>=3.10.8",
    "pre-commit>=4.5.1",
    "seaborn>=0.13.2",
    "torch>=2.11.0",
    "torchcodec>=0.11.1",
    "torchmetrics>=1.9.0",
    "torchvision>=0.26.0",
]


[dependency-groups]
dev = [
    "black>=26.3.1",
    "isort>=8.0.1",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
]


[build-system]
requires = ["uv_build>=0.6.0,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "tubevit"
module-root = ""


[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
    "E", # pycodestyle error
    "F", # Pyflakes
    "I", # isort
    "PLE", # Pylint error
    "PLW", # Pylint warning
]
ignore = []

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["F841", "F541"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "__pycache__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py312"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
py_version = 312
profile = "black"
